// These are the interfaces for all the states in this game
import { IBaseGameObjectState, IBaseGameState, IBasePlayerState } from "src/viseur/game";

// This is a file generated by the Creer, it may have empty interfaces,
// but we need them, so let's disable that tslint rule
// tslint:disable:no-empty-interface

/**
 * Convert as many humans to as you can to survive in this post-apocalyptic
 * wasteland.
 */
export interface IGameState extends IBaseGameState {
    /**
     * The multiplier for the amount of energy regenerated when resting in a
     * shelter with the cat overlord.
     */
    readonly catEnergyMult: number;

    /**
     * The player whose turn it is currently. That player can send commands.
     * Other players cannot.
     */
    readonly currentPlayer: IPlayerState;

    /**
     * The current turn number, starting at 0 for the first player's turn.
     */
    readonly currentTurn: number;

    /**
     * A mapping of every game object's ID to the actual game object. Primarily
     * used by the server and client to easily refer to the game objects via ID.
     */
    readonly gameObjects: {[id: string]: IGameObjectState};

    /**
     * The amount of turns it takes for a Tile that was just harvested to grow
     * food again.
     */
    readonly harvestCooldown: number;

    /**
     * All the Jobs that Units can have in the game.
     */
    readonly jobs: IJobState[];

    /**
     * The amount that the harvest rate is lowered each season.
     */
    readonly lowerHarvestAmount: number;

    /**
     * The number of Tiles in the map along the y (vertical) axis.
     */
    readonly mapHeight: number;

    /**
     * The number of Tiles in the map along the x (horizontal) axis.
     */
    readonly mapWidth: number;

    /**
     * The maximum number of turns before the game will automatically end.
     */
    readonly maxTurns: number;

    /**
     * The multiplier for the cost of actions when performing them in range of a
     * monument. Does not effect pickup cost.
     */
    readonly monumentCostMult: number;

    /**
     * The number of materials in a monument.
     */
    readonly monumentMaterials: number;

    /**
     * The number of materials in a neutral Structure.
     */
    readonly neutralMaterials: number;

    /**
     * List of all the players in the game.
     */
    readonly players: IPlayerState[];

    /**
     * A unique identifier for the game instance that is being played.
     */
    readonly session: string;

    /**
     * The number of materials in a shelter.
     */
    readonly shelterMaterials: number;

    /**
     * The multiplier for the amount of energy regenerated when resting while
     * starving.
     */
    readonly starvingEnergyMult: number;

    /**
     * Every Structure in the game.
     */
    readonly structures: IStructureState[];

    /**
     * All the tiles in the map, stored in Row-major order. Use `x + y *
     * mapWidth` to access the correct index.
     */
    readonly tiles: ITileState[];

    /**
     * After a food tile is harvested, the number of turns before it can be
     * harvested again.
     */
    readonly turnsBetweenHarvests: number;

    /**
     * The number of turns between fresh humans being spawned on the road.
     */
    readonly turnsToCreateHuman: number;

    /**
     * The number of turns before the harvest rate is lowered (length of each
     * season basically).
     */
    readonly turnsToLowerHarvest: number;

    /**
     * Every Unit in the game.
     */
    readonly units: IUnitState[];

    /**
     * The number of materials in a wall.
     */
    readonly wallMaterials: number;

}

/**
 * An object in the game. The most basic class that all game classes should
 * inherit from automatically.
 */
export interface IGameObjectState extends IBaseGameObjectState {
    /**
     * String representing the top level Class that this game object is an
     * instance of. Used for reflection to create new instances on clients, but
     * exposed for convenience should AIs want this data.
     */
    readonly gameObjectName: string;

    /**
     * A unique id for each instance of a GameObject or a sub class. Used for
     * client and server communication. Should never change value after being
     * set.
     */
    readonly id: string;

    /**
     * Any strings logged will be stored here. Intended for debugging.
     */
    readonly logs: string[];

}

/**
 * Information about a Unit's job.
 */
export interface IJobState extends IGameObjectState {
    /**
     * The amount of energy this Job normally uses to perform its actions.
     */
    readonly actionCost: number;

    /**
     * How many combined resources a Unit with this Job can hold at once.
     */
    readonly carryLimit: number;

    /**
     * The number of moves this Job can make per turn.
     */
    readonly moves: number;

    /**
     * The amount of energy normally regenerated when resting at a shelter.
     */
    readonly regenRate: number;

    /**
     * The Job title.
     */
    readonly title: string;

    /**
     * The amount of food per turn this Unit consumes. If there isn't enough
     * food for every Unit, all Units become starved and do not consume food.
     */
    readonly upkeep: number;

}

/**
 * A player in this game. Every AI controls one player.
 */
export interface IPlayerState extends IGameObjectState, IBasePlayerState {
    /**
     * The overlord cat Unit owned by this Player.
     */
    readonly cat: IUnitState;

    /**
     * What type of client this is, e.g. 'Python', 'JavaScript', or some other
     * language. For potential data mining purposes.
     */
    readonly clientType: string;

    /**
     * The amount of food owned by this player.
     */
    readonly food: number;

    /**
     * If the player lost the game or not.
     */
    readonly lost: boolean;

    /**
     * The name of the player.
     */
    readonly name: string;

    /**
     * This player's opponent in the game.
     */
    readonly opponent: IPlayerState;

    /**
     * The reason why the player lost the game.
     */
    readonly reasonLost: string;

    /**
     * The reason why the player won the game.
     */
    readonly reasonWon: string;

    /**
     * Every Structure owned by this Player.
     */
    readonly structures: IStructureState[];

    /**
     * The amount of time (in ns) remaining for this AI to send commands.
     */
    readonly timeRemaining: number;

    /**
     * Every Unit owned by this Player.
     */
    readonly units: IUnitState[];

    /**
     * The total upkeep of every Unit owned by this Player. If there isn't
     * enough food for every Unit, all Units become starved and do not consume
     * food.
     */
    readonly upkeep: number;

    /**
     * If the player won the game or not.
     */
    readonly won: boolean;

}

/**
 * A structure on a Tile.
 */
export interface IStructureState extends IGameObjectState {
    /**
     * The range of this Structure's effect. For example, a radius of 1 means
     * this Structure affects a 3x3 square centered on this Structure.
     */
    readonly effectRadius: number;

    /**
     * The number of materials in this Structure. Once this number reaches 0,
     * this Structure is destroyed.
     */
    readonly materials: number;

    /**
     * The owner of this Structure if any, otherwise null.
     */
    readonly owner: IPlayerState;

    /**
     * The Tile this Structure is on.
     */
    readonly tile: ITileState;

    /**
     * The type of Structure this is ('shelter', 'monument', 'wall', 'road',
     * 'neutral').
     */
    readonly type: string;

}

/**
 * A Tile in the game that makes up the 2D map grid.
 */
export interface ITileState extends IGameObjectState {
    /**
     * The number of food dropped on this Tile.
     */
    readonly food: number;

    /**
     * The amount of food that can be harvested from this Tile per turn.
     */
    readonly harvestRate: number;

    /**
     * The number of materials dropped on this Tile.
     */
    readonly materials: number;

    /**
     * The Structure on this Tile if present, otherwise null.
     */
    readonly structure: IStructureState;

    /**
     * The Tile to the 'East' of this one (x+1, y). Null if out of bounds of the
     * map.
     */
    readonly tileEast: ITileState;

    /**
     * The Tile to the 'North' of this one (x, y-1). Null if out of bounds of
     * the map.
     */
    readonly tileNorth: ITileState;

    /**
     * The Tile to the 'South' of this one (x, y+1). Null if out of bounds of
     * the map.
     */
    readonly tileSouth: ITileState;

    /**
     * The Tile to the 'West' of this one (x-1, y). Null if out of bounds of the
     * map.
     */
    readonly tileWest: ITileState;

    /**
     * The amount of turns before this resource can be harvested.
     */
    readonly turnsToHarvest: number;

    /**
     * The Unit on this Tile if present, otherwise null.
     */
    readonly unit: IUnitState;

    /**
     * The x (horizontal) position of this Tile.
     */
    readonly x: number;

    /**
     * The y (vertical) position of this Tile.
     */
    readonly y: number;

}

/**
 * A unit in the game.
 */
export interface IUnitState extends IGameObjectState {
    /**
     * Whether this Unit has performed its action this turn.
     */
    readonly acted: boolean;

    /**
     * The amount of energy this Unit has (from 0.0 to 100.0).
     */
    readonly energy: number;

    /**
     * The amount of food this Unit is holding.
     */
    readonly food: number;

    /**
     * The Job this Unit was recruited to do.
     */
    readonly job: IJobState;

    /**
     * The amount of materials this Unit is holding.
     */
    readonly materials: number;

    /**
     * The tile this Unit is moving to. This only applies to neutral fresh
     * humans spawned on the road. Otherwise, the tile this Unit is on.
     */
    readonly movementTarget: ITileState;

    /**
     * How many moves this Unit has left this turn.
     */
    readonly moves: number;

    /**
     * The Player that owns and can control this Unit, or null if the Unit is
     * neutral.
     */
    readonly owner: IPlayerState;

    /**
     * The Units in the same squad as this Unit. Units in the same squad attack
     * and defend together.
     */
    readonly squad: IUnitState[];

    /**
     * Whether this Unit is starving. Starving Units regenerate energy at half
     * the rate they normally would while resting.
     */
    readonly starving: boolean;

    /**
     * The Tile this Unit is on.
     */
    readonly tile: ITileState;

    /**
     * The number of turns before this Unit dies. This only applies to neutral
     * fresh humans created from combat. Otherwise, 0.
     */
    readonly turnsToDie: number;

}
