// These are the interfaces for all the states in this game
import { IBaseGame, IBaseGameObject, IBasePlayer } from "@cadre/ts-utils/cadre";

// This is a file generated by the Creer, it may have empty interfaces,
// but we need them, so let's disable that tslint rule
// tslint:disable:no-empty-interface

/**
 * Combine elements and be the first scientists to create fusion.
 */
export interface IGameState extends IBaseGame {
    /**
     * The player whose turn it is currently. That player can send commands.
     * Other players cannot.
     */
    currentPlayer: IPlayerState;

    /**
     * The current turn number, starting at 0 for the first player's turn.
     */
    currentTurn: number;

    /**
     * Percent loss from the difference of Heat and Pressure. (0 to 1).
     */
    degradeRate: number;

    /**
     * A mapping of every game object's ID to the actual game object. Primarily
     * used by the server and client to easily refer to the game objects via ID.
     */
    gameObjects: {[id: string]: IGameObjectState};

    /**
     * The maximum number of interns a player can have.
     */
    internCap: number;

    /**
     * A list of all jobs. first item is intern, second is physicists, and third
     * is manager.
     */
    jobs: IJobState[];

    /**
     * Every Machine in the game.
     */
    machines: IMachineState[];

    /**
     * The maximum number of managers a player can have.
     */
    managerCap: number;

    /**
     * The number of Tiles in the map along the y (vertical) axis.
     */
    mapHeight: number;

    /**
     * The number of Tiles in the map along the x (horizontal) axis.
     */
    mapWidth: number;

    /**
     * The number of materials that spawn per spawn cycle.
     */
    materialSpawn: number;

    /**
     * The maximum number of turns before the game will automatically end.
     */
    maxTurns: number;

    /**
     * The maximum number of physicists a player can have.
     */
    physicistCap: number;

    /**
     * List of all the players in the game.
     */
    players: IPlayerState[];

    /**
     * The amount of victory points added when a refined ore is consumed by the
     * generator.
     */
    refinedValue: number;

    /**
     * A unique identifier for the game instance that is being played.
     */
    session: string;

    /**
     * The amount of turns it takes a unit to spawn.
     */
    spawnTime: number;

    /**
     * The amount of turns a unit cannot do anything when stunned.
     */
    stunTime: number;

    /**
     * All the tiles in the map, stored in Row-major order. Use `x + y *
     * mapWidth` to access the correct index.
     */
    tiles: ITileState[];

    /**
     * The amount of time (in nano-seconds) added after each player performs a
     * turn.
     */
    timeAddedPerTurn: number;

    /**
     * The number turns a unit is immune to being stunned.
     */
    timeImmune: number;

    /**
     * Every Unit in the game.
     */
    units: IUnitState[];

    /**
     * The amount of combined heat and pressure that you need to win.
     */
    victoryAmount: number;

}

/**
 * An object in the game. The most basic class that all game classes should
 * inherit from automatically.
 */
export interface IGameObjectState extends IBaseGameObject {
    /**
     * String representing the top level Class that this game object is an
     * instance of. Used for reflection to create new instances on clients, but
     * exposed for convenience should AIs want this data.
     */
    gameObjectName: string;

    /**
     * A unique id for each instance of a GameObject or a sub class. Used for
     * client and server communication. Should never change value after being
     * set.
     */
    id: string;

    /**
     * Any strings logged will be stored here. Intended for debugging.
     */
    logs: string[];

}

/**
 * Information about a unit's job.
 */
export interface IJobState extends IGameObjectState {
    /**
     * How many combined resources a unit with this Job can hold at once.
     */
    carryLimit: number;

    /**
     * The amount of damage this Job does per attack.
     */
    damage: number;

    /**
     * The amount of starting health this Job has.
     */
    health: number;

    /**
     * The number of moves this Job can make per turn.
     */
    moves: number;

    /**
     * The Job title. 'intern', 'manager', or 'physicist'.
     */
    title: string;

}

/**
 * A machine in the game. Used to refine ore.
 */
export interface IMachineState extends IGameObjectState {
    /**
     * What type of ore the machine takes it. Also determines the type of
     * material it outputs. (redium or blueium).
     */
    oreType: string;

    /**
     * The amount of ore that needs to be inputted into the machine for it to be
     * worked.
     */
    refineInput: number;

    /**
     * The amount of refined ore that is returned after the machine has been
     * fully worked.
     */
    refineOutput: number;

    /**
     * The number of times this machine needs to be worked to refine ore.
     */
    refineTime: number;

    /**
     * The Tile this Machine is on.
     */
    tile: ITileState;

    /**
     * Tracks how many times this machine has been worked. (0 to refineTime).
     */
    worked: number;

}

/**
 * A player in this game. Every AI controls one player.
 */
export interface IPlayerState extends IGameObjectState, IBasePlayer {
    /**
     * What type of client this is, e.g. 'Python', 'JavaScript', or some other
     * language. For potential data mining purposes.
     */
    clientType: string;

    /**
     * Every generator Tile owned by this Player. (listed from the outer edges
     * inward, from top to bottom).
     */
    generatorTiles: ITileState[];

    /**
     * The amount of heat this Player has.
     */
    heat: number;

    /**
     * The time left till a intern spawns. (0 to spawnTime).
     */
    internSpawn: number;

    /**
     * If the player lost the game or not.
     */
    lost: boolean;

    /**
     * The time left till a manager spawns. (0 to spawnTime).
     */
    managerSpawn: number;

    /**
     * The name of the player.
     */
    name: string;

    /**
     * This player's opponent in the game.
     */
    opponent: IPlayerState;

    /**
     * The time left till a physicist spawns. (0 to spawnTime).
     */
    physicistSpawn: number;

    /**
     * The amount of pressure this Player has.
     */
    pressure: number;

    /**
     * The reason why the player lost the game.
     */
    reasonLost: string;

    /**
     * The reason why the player won the game.
     */
    reasonWon: string;

    /**
     * All the tiles this Player's units can spawn on. (listed from the outer
     * edges inward, from top to bottom).
     */
    spawnTiles: ITileState[];

    /**
     * The amount of time (in ns) remaining for this AI to send commands.
     */
    timeRemaining: number;

    /**
     * Every Unit owned by this Player.
     */
    units: IUnitState[];

    /**
     * If the player won the game or not.
     */
    won: boolean;

}

/**
 * A Tile in the game that makes up the 2D map grid.
 */
export interface ITileState extends IGameObjectState {
    /**
     * The amount of blueium on this tile.
     */
    blueium: number;

    /**
     * The amount of blueium ore on this tile.
     */
    blueiumOre: number;

    /**
     * (Visualizer only) Different tile types, cracked, slightly dirty, etc.
     * This has no effect on gameplay, but feel free to use it if you want.
     */
    decoration: number;

    /**
     * The direction of a conveyor belt ('blank', 'north', 'east', 'south', or
     * 'west'). blank means conveyor doesn't move.
     */
    direction: string;

    /**
     * Whether or not the tile is a wall.
     */
    isWall: boolean;

    /**
     * The Machine on this Tile if present, otherwise null.
     */
    machine: IMachineState;

    /**
     * The owner of this Tile, or null if owned by no-one. Only for generators
     * and spawn areas.
     */
    owner: IPlayerState;

    /**
     * The amount of redium on this tile.
     */
    redium: number;

    /**
     * The amount of redium ore on this tile.
     */
    rediumOre: number;

    /**
     * The Tile to the 'East' of this one (x+1, y). Null if out of bounds of the
     * map.
     */
    tileEast: ITileState;

    /**
     * The Tile to the 'North' of this one (x, y-1). Null if out of bounds of
     * the map.
     */
    tileNorth: ITileState;

    /**
     * The Tile to the 'South' of this one (x, y+1). Null if out of bounds of
     * the map.
     */
    tileSouth: ITileState;

    /**
     * The Tile to the 'West' of this one (x-1, y). Null if out of bounds of the
     * map.
     */
    tileWest: ITileState;

    /**
     * The type of Tile this is ('normal', 'generator', 'conveyor', or 'spawn').
     */
    type: string;

    /**
     * The Unit on this Tile if present, otherwise null.
     */
    unit: IUnitState;

    /**
     * The x (horizontal) position of this Tile.
     */
    x: number;

    /**
     * The y (vertical) position of this Tile.
     */
    y: number;

}

/**
 * A unit in the game. May be a manager, intern, or physicist.
 */
export interface IUnitState extends IGameObjectState {
    /**
     * Whether or not this Unit has performed its action this turn.
     */
    acted: boolean;

    /**
     * The amount of blueium carried by this unit. (0 to job carry capacity -
     * other carried items).
     */
    blueium: number;

    /**
     * The amount of blueium ore carried by this unit. (0 to job carry capacity
     * - other carried items).
     */
    blueiumOre: number;

    /**
     * The remaining health of a unit.
     */
    health: number;

    /**
     * The Job this Unit has.
     */
    job: IJobState;

    /**
     * The number of moves this unit has left this turn.
     */
    moves: number;

    /**
     * The Player that owns and can control this Unit.
     */
    owner: IPlayerState;

    /**
     * The amount of redium carried by this unit. (0 to job carry capacity -
     * other carried items).
     */
    redium: number;

    /**
     * The amount of redium ore carried by this unit. (0 to job carry capacity -
     * other carried items).
     */
    rediumOre: number;

    /**
     * Duration of stun immunity. (0 to timeImmune).
     */
    stunImmune: number;

    /**
     * Duration the unit is stunned. (0 to the game constant stunTime).
     */
    stunTime: number;

    /**
     * The Tile this Unit is on.
     */
    tile: ITileState;

}
